version: 2.1

jobs:
  run-hello:
    docker:
      - image : circleci/python:3.8
    steps:
      - checkout
      - run :
          name : Run hello.py
          command: python hello.py
  
  run-bye:

    docker:
     - image: circleci/python:3.8
    steps:
      - checkout
      - run :
          name : Run bye.py
          command: python bye.py

workflows:
  version: 2
  run-and-test:
    jobs:
      - run-hello:
          filters:
            branches:
              only:
                - main
                - test
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
                

      - run-bye:
          filters:
            branches:
              only:
                - test
                - main
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
